package PriorityQueueApp;

public enum RequestType {
	OTHER,
	CHANGE_ACCOUNT_DETAILS,
	CAN_NOT_LOGIN,
	ACCOUNT_IS_BLOCKED,
	COOPERATION,
	ACCOUNT_IS_HACKED,
	CAN_NOT_COMPLETE_PURCHASE,
	ORDER_IS_NOT_RECEIVED,


}
